services:
  app:
    image: imessage-decrypt-export:latest
    build: .
    tty: true
    environment:
      - BACKUP_ROOT="$HOME/Library/Application Support/MobileSync/Backup"
      - EXPORT_ROOT="$HOME/Export"
    volumes:
      - type: bind
        source: $BACKUP_ROOT
        target: /mnt/Backup
      - type: bind
        source: $EXPORT_ROOT
        target: /mnt/Export